name: Deploy to Skynet

on:
  push:
    branches: [main, v3-flash-swaps]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: dapp
          skynet-jwt: ${{ secrets.SKYNET_JWT || '' }}
          portal-url: https://fileportal.org
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
